### ISSUE TITLE
大佬照着教程得到了API但是填入后一直提示是无效的跟我是把插件从本地导入有关系吗？

### ISSUE THREAD

**Issue by HuaYan-y** [NukoOoOoOoO/FFLogsViewer#1]

**Comment by Nukoooo** [comment]
跟从本地导入没关系。我刚刚创建了一个API Client试了一下是可以用的，可能是网的问题或者是别的乱七八糟的问题？我之前在重装系统完之后有一段时间是说API Client无效，但登录了我自己的FFLogs账号之后就可以用了

**Comment by HuaYan-y** [comment]
好哦，谢谢大佬今天我换个网再试试

**Comment by Nukoooo** [comment]
先关issue了，如果还有问题的话可以再开
