### ISSUE TITLE
新发布的S怪小助手插件会把游戏给整个炸掉并且无法再次启动

### ISSUE THREAD

**Issue by HeavenPolicy** [NukoOoOoOoO/FFLogsViewer#2]
查看新插件的时候看到S怪农怪插件并且点了安装，游戏立刻爆炸并且无法再次正常打开游戏，重新装载了一套新的插件之后才恢复

**Comment by NukoOoOoOoO** [comment]
应该是创建字体时发生了问题，我在写的时候也遇到过。那个插件到时候我会新开一个repository，就不用到这里开issue了(顺带一提那个插件是给触发用的)
