### ISSUE TITLE
名字搜索栏无法输入长度大于5位的名字

### ISSUE THREAD

**Issue by HakureiHyouga** [NukoOoOoOoO/FFLogsViewer#3]
名字如“一二三四五六”的这种6位中文名，只能输入五位，复制粘贴进去也不行，会变成“一二三四五”
但是右键菜单直接点击搜索却可以（可是如果有人改名的话，就不能直接右键了，需要手动输入）
这个可以修正吗？
![Snipaste_2022-08-24_18-54-00](https://user-images.githubusercontent.com/12714574/186401110-53f76e27-ad8d-47f2-87fa-b3b91e62a0e6.jpg)

**Comment by Nukoooo** [comment]
感谢反馈,待会会更新

**Comment by Nukoooo** [comment]
应该是修复了，如果还有问题的话可以把本issue重开
