### ISSUE TITLE
插件下载失败

### ISSUE THREAD

**Issue by 562646310** [NukoOoOoOoO/FFLogsViewer#4]
按照操作步骤添加自定义插件仓库，返回插件管理器提示下载失败
![image](https://user-images.githubusercontent.com/71921402/202100542-0be6120d-9410-4de4-8a98-19557f31bb32.png)
后面科学上网更换多个节点也是下载失败_(:з」∠)_
用原版英文的插件也提示下载失败_(:з」∠)_
已经不知道是我的网络问题还是步骤哪里不对了，求解答

**Comment by Nukoooo** [comment]
如果我没记错的话，SSR是不会代理卫月的，我比较建议在路由器上搭梯子，这样就不用担心下载失败啥的。除了在路由器上搭梯子以外，我能想到的解决办法有:

- 在Dalamud设置里的测试版页面下，把最下面的``Use System Proxy``给取消打勾，然后把Proxy Host和Proxy Port改成你梯子所代理的地址和端口（一般只需要改端口）。举个例子，我用Clash，然后它代理的端口是5678，那Proxy Port就改成5678
- 添加Fuck GFW替换
- 使用 [GHProxy](https://ghproxy.com/)
- 使用 [FastGithub](https://github.com/dotnetcore/FastGithub)

**Comment by 562646310** [comment]
谢谢大佬指点，不过搭梯子代理我这里还是无法下载，是用了本地导入开发版插件的方法装上的，还是谢谢您！啵啵
