### ISSUE TITLE
Author/Naming addition

### ISSUE THREAD

**Issue by Aireil** [NukoOoOoOoO/FFLogsViewer#5]
Hey, if possible, could you please add information about this being for the Chinese client in the manifest of your repo?
Maybe just adding your name to `Author` and something like (Chinese version) to the `Name` field.

Recently got an issue with your fork overwriting my repo on mega repos cf [my issue](https://www.github.com/Akurosia/MyCustomDalamudPluginRepoCollection/issues/20) and [the issue on my repo.](https://www.github.com/Aireil/FFLogsViewer/issues/27)
This would at least be clearer for people looking in the installer, should anything alike happen again.

We should have used a different InternalName for the version you're maintaining, but I never thought of that at the time. Don't change the InternalName now though, otherwise people with your repo installed won't get the updates without reinstalling. It's not worth it hehe.

Thank you~

**Comment by Nukoooo** [comment]
[Like this?](https://github.com/NukoOoOoOoO/FFLogsViewer/commit/6eb6edcca6368ae84781d50768bd5ca66d3adff5)

**Comment by Aireil** [comment]
Perfect, thank you!
