### ISSUE TITLE
无论是否组队，在“小队成员”中都一直显示“找不到小队成员”

### ISSUE THREAD

**Issue by etnAtker** [NukoOoOoOoO/FFLogsViewer#6]
如题，无论是否组队，在“小队成员”中都一直显示“找不到小队成员”，如图所示。
![image](https://github.com/Nukoooo/FFLogsViewer/assets/20952240/31dd338f-c798-4eaa-8da8-1cbbf9767fcc)

请问是哪里配置不正确吗？用右键菜单查询则正常

**Comment by Nukoooo** [comment]
已修复
