### ISSUE TITLE
更新后使用时发生错误：World not supported or invalid

### ISSUE THREAD

**Issue by haku-huang** [NukoOoOoOoO/FFLogsViewer#7]
在2023/7/30日更新后出现此问题，复现率100%，经初步排查可能是目前请求的url路径有一些问题。
例如在浏览器中打开，实际访问链接为：https://cn.fflogs.com/character//{worldName}/{userName}
版本号：v2.1.4.1

**Comment by Nukoooo** [comment]
是在哪儿请求logs的,我这儿请求是没问题的

**Comment by haku-huang** [comment]
豆豆柴 红茶川

**Comment by Nukoooo** [comment]
应该修复了,如果还有问题的话可以重新开这个issue
