### ISSUE TITLE
根据简介操作进行设置API后显示Could not reach FF Logs servers

### ISSUE THREAD

**Issue by Zombieterry** [NukoOoOoOoO/FFLogsViewer#8]
如题，API显示设置成功，但插件搜索任意一人后，界面提示“无法连接到Logs服务器”

**Comment by Nukoooo** [comment]
一般是网络问题, 看看你的代理软件有没有代理卫月. 

- 如果没有的话, 用clash然后把TUN模式打开应该就可以了.
- 如果是在国外的话, 一般是加速器代理卫月了, 关掉或者换成路由模式应该就能解决

**Comment by Zombieterry** [comment]
开了TUN模式连大厅服务器都登不上了，人在国内，但是开着代理国际服的这个插件是可以正常用的

**Comment by Nukoooo** [comment]
我是用的Clash Verge, 设置是系统代理+TUN模式+Service Mode, 然后路由器上也有代理, 所以我没办法复现这个问题.
